# Generated by Django 5.2.17 on 2026-09-25 10:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('content', models.TextField(max_length=1000, verbose_name='Zawartość')),
            ],
            options={
                'verbose_name': 'Strona startowa',
                'verbose_name_plural': 'Strona startowa',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nazwa instytucji')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefon')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Data wprowadzenia')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Strona internetowa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('type', models.CharField(choices=[('P', 'Publiczna'), ('N', 'Naukowa')], max_length=1, verbose_name='Typ biblioteki')),
                ('chain', models.CharField(choices=[('P', 'Publiczna'), ('N', 'Naukowa')], max_length=1, verbose_name='Sieć bibliotek')),
                ('owner', models.CharField(db_index=True, max_length=100, verbose_name='Organizator')),
                ('siglum', models.CharField(blank=True, max_length=15, verbose_name='Siglum')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('street', models.CharField(blank=True, max_length=128, verbose_name='Ulica')),
                ('zip_code', models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Miasto')),
                ('state', models.CharField(choices=[('0', 'Dolnośląskie'), ('1', 'Kujawsko-pomorskie'), ('2', 'Lubelskie'), ('3', 'Lubuskie'), ('4', 'Łódzkie'), ('5', 'Małopolskie'), ('6', 'Mazowieckie'), ('7', 'Opolskie'), ('8', 'Podkarpackie'), ('9', 'Podlaskie'), ('10', 'Pomorskie'), ('11', 'Śląskie'), ('12', 'Świętokrzyskie'), ('13', 'Warmińsko-mazurskie'), ('14', 'Wielkopolskie'), ('15', 'Zachodniopomorskie')], max_length=2, verbose_name='Województwo')),
                ('status', models.CharField(choices=[('N', 'Nieaktywny'), ('A', 'Aktywny')], default='A', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Biblioteka',
                'verbose_name_plural': 'Biblioteki',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'city'], name='directory_l_status_04d905_idx'), models.Index(fields=['type', 'chain', 'state'], name='directory_l_type_071b23_idx')],
            },
        ),
    ]
