# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Biblioteka', 'verbose_name_plural': 'Biblioteki'},
        ),
    ]
