# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0002_auto_20161230_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Biblioteka_adres', 'verbose_name_plural': 'Biblioteki_adres'},
        ),
    ]
