# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0003_auto_20170115_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='library',
        ),
        migrations.AddField(
            model_name='library',
            name='city',
            field=models.CharField(default=b'Miasto', max_length=50, verbose_name=b'Miasto'),
        ),
        migrations.AddField(
            model_name='library',
            name='state',
            field=models.CharField(default=b'Mazowieckie', max_length=50, verbose_name='Wojew\xf3dztwo'),
        ),
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[(b'N', b'Nieaktywny'), (b'A', b'Aktywny')], default=b'A', max_length=1, verbose_name=b'Status'),
        ),
        migrations.AddField(
            model_name='library',
            name='street',
            field=models.CharField(default=b'Ulica', max_length=128, verbose_name=b'Ulica'),
        ),
        migrations.AddField(
            model_name='library',
            name='zip_code',
            field=models.CharField(default=b'00000', max_length=5, verbose_name=b'Kod pocztowy'),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
