# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0004_auto_20170316_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'U', b'Unactive')], default=b'A', max_length=1, verbose_name=b'Status'),
        ),
    ]
