# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0005_auto_20170321_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='state',
            field=models.CharField(choices=[(b'0', 'Dolno\u015bl\u0105skie'), (b'1', b'Kujawsko-pomorskie'), (b'2', b'Lubelskie'), (b'3', b'Lubuskie'), (b'4', '\u0141\xf3dzkie'), (b'5', 'Ma\u0142opolskie'), (b'6', b'Mazowieckie'), (b'7', b'Opolskie'), (b'8', b'Podkarpackie'), (b'9', b'Podlaskie'), (b'10', b'Pomorskie'), (b'11', '\u015al\u0105skie'), (b'12', '\u015awi\u0119tokrzyskie'), (b'13', 'Warmi\u0144sko-mazurskie'), (b'14', b'Wielkopolskie'), (b'15', b'Zachodniopomorskie')], default=b'Mazowieckie', max_length=50, verbose_name='Wojew\xf3dztwo'),
        ),
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[(b'N', b'Nieaktywny'), (b'A', b'Aktywny')], default=b'A', max_length=1, verbose_name=b'Status'),
        ),
    ]
