# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 21:27
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0007_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Strona startowa'},
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=redactor.fields.RedactorField(max_length=1000, verbose_name=b'Zawarto\xc5\x9b\xc4\x87'),
        ),
    ]
