# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 20:53
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0008_auto_20170330_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='notes',
            field=redactor.fields.RedactorField(verbose_name=b'Uwagi'),
        ),
        migrations.AlterField(
            model_name='library',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=b'+48123456789', max_length=128, verbose_name=b'Telefon'),
        ),
    ]
