# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(default=b'Miasto', max_length=50, verbose_name=b'Miasto'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='state',
            field=models.CharField(default=b'Mazowieckie', max_length=50, verbose_name='Wojew\xf3dztwo'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='status',
            field=models.CharField(choices=[(b'N', b'Nieaktywny'), (b'A', b'Aktywny')], default=b'N', max_length=1, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(default=b'Ulica', max_length=128, verbose_name=b'Ulica'),
        ),
        migrations.RemoveField(
            model_name='biblioteka',
            name='adres',
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='adres',
            field=models.ForeignKey(default=b'adres', on_delete=django.db.models.deletion.CASCADE, to='entity.Adress'),
        ),
        migrations.RemoveField(
            model_name='biblioteka',
            name='email',
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='email',
            field=models.ForeignKey(default=b'adres@email.pl', on_delete=django.db.models.deletion.CASCADE, to='entity.Email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default=b'adres@email.pl', max_length=254, verbose_name=b'adres e-mail'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[(b'N', b'Nieaktywny'), (b'A', b'Aktywny')], default=b'N', max_length=1, verbose_name=b'Status'),
        ),
    ]
