# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20161221_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteka',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='biblioteka',
            name='email',
        ),
        migrations.AlterField(
            model_name='adress',
            name='status',
            field=models.CharField(choices=[(b'N', b'Nieaktywny'), (b'A', b'Aktywny')], max_length=1, verbose_name=b'Status'),
        ),
    ]
